### ISSUE TITLE
Error on `rails console`

### ISSUE THREAD

**Issue by j0an** [MrEmelianenko/drape#1]
Hi

I'm getting this error when I try to enter to `rails console` on a Rails 5.1.3

```$ rails c
Running via Spring preloader in process 380
/usr/local/bundle/gems/actionpack-5.1.3/lib/action_controller/test_case.rb:39:in `create': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /usr/local/bundle/gems/drape-1.0.0.beta1/lib/drape/view_context/build_strategy.rb:40:in `block in controller'
	from /usr/local/bundle/gems/drape-1.0.0.beta1/lib/drape/view_context/build_strategy.rb:39:in `tap'
	from /usr/local/bundle/gems/drape-1.0.0.beta1/lib/drape/view_context/build_strategy.rb:39:in `controller'
	from /usr/local/bundle/gems/drape-1.0.0.beta1/lib/drape/view_context/build_strategy.rb:29:in `call'
	from /usr/local/bundle/gems/drape-1.0.0.beta1/lib/drape/view_context.rb:49:in `build'
	from /usr/local/bundle/gems/drape-1.0.0.beta1/lib/drape/railtie.rb:62:in `block in <class:Railtie>'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/railtie.rb:228:in `block in run_console_blocks'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/railtie.rb:250:in `each'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/railtie.rb:250:in `each_registered_block'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/railtie.rb:228:in `run_console_blocks'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/application.rb:460:in `block in run_console_blocks'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/engine/railties.rb:13:in `each'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/engine/railties.rb:13:in `each'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/application.rb:460:in `run_console_blocks'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/engine.rb:442:in `load_console'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/commands/console/console_command.rb:27:in `initialize'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/commands/console/console_command.rb:17:in `new'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/commands/console/console_command.rb:17:in `start'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/commands/console/console_command.rb:85:in `perform'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/command/base.rb:63:in `perform'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/command.rb:44:in `invoke'
	from /usr/local/bundle/gems/railties-5.1.3/lib/rails/commands.rb:16:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /home/dashboard/bin/rails:9:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `load'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `block in load'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `load'
	from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'```


any thought?

**Comment by akodkod** [comment]
@j0an looks like `ActionController::TestCase` were updated. I'll check it this weekend.

But I suggest you use my new gem with decorator pattern, it's more efficient and lightweight:
– https://github.com/light-ruby/light-decorator

**Comment by j0an** [comment]
Oh oh. I will try it later :)

-- 
Juan Manuel Garcia Olivares
